// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://qknnbsflsvxigfiwkehs.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbm5ic2Zsc3Z4aWdmaXdrZWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjU4MDcsImV4cCI6MjA2OTIwMTgwN30.coSJxzla3QHYK3xKNO0T1Bqc2vErnwXoTdSVj9awTlQ";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });